"""
Django settings for school_project project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import environ



env = environ.Env(  
    # set casting, default value  
    DEBUG=(bool, False)  
)  

BASE_DIR = Path(__file__).resolve().parent.parent
# Load local overrides first (school_project/.env: DATABASE_URL, DROPBOX etc.)
# Then fill remaining gaps from app defaults (school_app/.env: SECRET_KEY, API keys etc.)
# Values set by the first file are NOT overwritten by the second (overwrite=False is default).
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))
environ.Env.read_env(os.path.join(BASE_DIR, "school_app", ".env"), overwrite=False)

SECRET_KEY = env("SECRET_KEY")  # No default — app crashes at startup if not set in .env

DEBUG = env("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

AUTH_USER_MODEL = 'school_app.CustomUser'


# Expire sessions after 30 minutes of inactivity
SESSION_COOKIE_AGE = 60 * 30  # 30 minutes
SESSION_SAVE_EVERY_REQUEST = True  # Reset timer on every request
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # End session when browser is closed
SESSION_COOKIE_HTTPONLY = True  # Prevent JS access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection for session cookie
# Secure cookies: True in production (HTTPS), False for local HTTP dev.
# Override via SESSION_COOKIE_SECURE=False in .env when testing locally.
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=not DEBUG)
LOGIN_URL = '/login/'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap4',
    'school_app',
    'dbbackup', 
    'captcha', 
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'school_app.middleware.SecurityMiddleware',
]

ROOT_URLCONF = 'school_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_project.wsgi.application'


WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# Use environment variable DATABASE_URL if available, otherwise use PostgreSQL config
DATABASES = {
    'default': env.db(
        default='postgresql://postgres:postgres@localhost:5432/padhaiwithai_19022026'
    )
}
# Enable WAL mode for SQLite
from django.db.backends.signals import connection_created
from django.dispatch import receiver

@receiver(connection_created)
def enable_wal_mode(sender, connection, **kwargs):
    if connection.vendor == 'sqlite':
        cursor = connection.cursor()
        cursor.execute('PRAGMA journal_mode=WAL;')
        cursor.execute('PRAGMA synchronous=NORMAL;')
        cursor.execute('PRAGMA cache_size=-64000;')  # 64MB
        cursor.execute('PRAGMA foreign_keys=ON;')
        
        # Check and print the settings
        cursor.execute('PRAGMA journal_mode;')
        journal_mode = cursor.fetchone()[0]
        print(f"Journal mode: {journal_mode}")
        
        cursor.execute('PRAGMA synchronous;')
        sync_mode = cursor.fetchone()[0]
        print(f"Synchronous mode: {sync_mode}")
        
        cursor.execute('PRAGMA cache_size;')
        cache_size = cursor.fetchone()[0]
        print(f"Cache size: {cache_size}")
        
        cursor.execute('PRAGMA foreign_keys;')
        foreign_keys = cursor.fetchone()[0]
        print(f"Foreign keys: {foreign_keys}")

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

LOGGING = {  
    "version": 1,  
    "disable_existing_loggers": False,  
    "handlers": {"console": {"class": "logging.StreamHandler"}},  
    "loggers": {"": {"handlers": ["console"], "level": "DEBUG"}},  
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = env.str("STATIC_URL", default="/static/")  
STATIC_ROOT = env.str("STATIC_ROOT", default=BASE_DIR / "staticfiles")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'school_app/static'),
    os.path.join(BASE_DIR, 'school_app/content'),
]
CONTENT_DIR = os.path.join(BASE_DIR, 'school_app/content')

# Media settings
MEDIA_ROOT = env("MEDIA_ROOT", default=BASE_DIR / "media")  
MEDIA_URL = env("MEDIA_PATH", default="/media/")


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Backup settings
DBBACKUP_STORAGE = 'storages.backends.dropbox.DropBoxStorage'
DBBACKUP_STORAGE_OPTIONS = {
    'oauth2_access_token': env("DROPBOX_ACCESS_TOKEN"),
}

# Optional: Configure backup filename template
DBBACKUP_FILENAME_TEMPLATE = '{datetime}.{extension}'
DBBACKUP_CLEANUP_KEEP = 10  # Keep last 10 backups

# Optional: Backup Media Files too
DBBACKUP_CONNECTORS = {
    'default': {
        'ENGINE': 'dbbackup.db.postgresql.PgDumpConnector',
    }
}

# Django Simple Captcha Customization
CAPTCHA_LENGTH = 6
CAPTCHA_FONT_SIZE = 36
CAPTCHA_FOREGROUND_COLOR = '#FF0000'
CAPTCHA_BACKGROUND_COLOR = '#F5F5F5'
CAPTCHA_LETTER_ROTATION = (-20, 20)
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_arcs', 'captcha.helpers.noise_dots')
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'

# Security Headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# Account lockout settings
ACCOUNT_LOCKOUT_ATTEMPTS = 5
ACCOUNT_LOCKOUT_DURATION = 5  # minutes

# Password expiry (days) — for admin/district/state/block users
PASSWORD_EXPIRY_DAYS = 90

# Max file upload size (5 MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024