# Generated by Django 5.0 on 2024-12-29 06:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('MATH', 'Mathematics')], max_length=4)),
                ('class_level', models.CharField(choices=[('10', 'Class 10')], max_length=2)),
                ('question_paper', models.FileField(upload_to='test_papers/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('answer_key', models.FileField(upload_to='answer_keys/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
