# Generated by Django 5.0 on 2024-12-28 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_number', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=255)),
                ('subject_name', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='test_pdfs/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
