# Generated by Django 5.0 on 2024-12-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_testpaper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestPaper',
        ),
    ]
