# Generated by Django 5.0 on 2024-12-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
