# Generated by Django 5.0 on 2024-12-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_delete_testpaper'),
        ('school_app', '0006_test_test_date'),
    ]

    operations = [
    ]
