# Generated by Django 5.0 on 2024-12-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_merge_0006_delete_testpaper_0006_test_test_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='test',
            name='pdf_file_answers',
            field=models.FileField(blank=True, null=True, upload_to='test_pdfs/answers/'),
        ),
        migrations.AddField(
            model_name='test',
            name='pdf_file_questions',
            field=models.FileField(blank=True, null=True, upload_to='test_pdfs/questions/'),
        ),
    ]
