# Generated by Django 5.0 on 2024-12-31 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_remove_test_pdf_file_test_pdf_file_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_app.test'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student', 'test')},
        ),
    ]
