# Generated by Django 5.0 on 2024-12-31 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0009_marks_test_alter_marks_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='test_number',
        ),
    ]
