-- ============================================================
-- AI Sathi Curriculum Tables
-- Run this script on any PostgreSQL database
-- ============================================================

-- STEP 1: Create Tables
-- ============================================================

CREATE TABLE IF NOT EXISTS school_app_aisathiclass (
    id          BIGSERIAL PRIMARY KEY,
    number      SMALLINT    NOT NULL UNIQUE,
    is_active   BOOLEAN     NOT NULL DEFAULT true,
    "order"     SMALLINT    NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS school_app_aisathisubject (
    id          BIGSERIAL PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT true,
    "order"     SMALLINT     NOT NULL DEFAULT 0,
    class_ref_id BIGINT      NOT NULL REFERENCES school_app_aisathiclass(id) ON DELETE CASCADE,
    CONSTRAINT unique_class_subject UNIQUE (class_ref_id, name)
);

CREATE TABLE IF NOT EXISTS school_app_aisathichapter (
    id          BIGSERIAL PRIMARY KEY,
    name        VARCHAR(300) NOT NULL,
    "order"     SMALLINT     NOT NULL DEFAULT 0,
    is_active   BOOLEAN      NOT NULL DEFAULT true,
    subject_id  BIGINT       NOT NULL REFERENCES school_app_aisathisubject(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_aisathisubject_class   ON school_app_aisathisubject(class_ref_id);
CREATE INDEX IF NOT EXISTS idx_aisathichapter_subject ON school_app_aisathichapter(subject_id);

-- ============================================================
-- STEP 2: Insert Records
-- ============================================================

INSERT INTO school_app_aisathiclass (id, number, is_active, "order") VALUES (1, 6, true, 0);
INSERT INTO school_app_aisathiclass (id, number, is_active, "order") VALUES (2, 7, true, 1);
INSERT INTO school_app_aisathiclass (id, number, is_active, "order") VALUES (3, 8, true, 2);
INSERT INTO school_app_aisathiclass (id, number, is_active, "order") VALUES (4, 9, true, 3);
INSERT INTO school_app_aisathiclass (id, number, is_active, "order") VALUES (5, 10, true, 4);
INSERT INTO school_app_aisathiclass (id, number, is_active, "order") VALUES (6, 11, true, 5);
INSERT INTO school_app_aisathiclass (id, number, is_active, "order") VALUES (7, 12, true, 6);

INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (1, 'Math', true, 0, 1);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (2, 'Science', true, 1, 1);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (3, 'English', true, 2, 1);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (4, 'Hindi', true, 3, 1);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (5, 'Social Science', true, 4, 1);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (6, 'Math', true, 0, 2);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (7, 'Science', true, 1, 2);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (8, 'English', true, 2, 2);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (9, 'Hindi', true, 3, 2);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (10, 'Social Science', true, 4, 2);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (11, 'Math', true, 0, 3);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (12, 'Science', true, 1, 3);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (13, 'English', true, 2, 3);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (14, 'Hindi', true, 3, 3);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (15, 'Social Science', true, 4, 3);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (16, 'Computer Science', true, 5, 3);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (17, 'Physical Education', true, 6, 3);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (18, 'Math', true, 0, 4);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (19, 'Science', true, 1, 4);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (20, 'English', true, 2, 4);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (21, 'Hindi', true, 3, 4);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (22, 'Social Science', true, 4, 4);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (23, 'Computer Science', true, 5, 4);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (24, 'Physical Education', true, 6, 4);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (25, 'Math', true, 0, 5);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (26, 'Science', true, 1, 5);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (27, 'English', true, 2, 5);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (28, 'Hindi', true, 3, 5);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (29, 'Social Science', true, 4, 5);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (30, 'Computer Science', true, 5, 5);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (31, 'Physical Education', true, 6, 5);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (32, 'Physics', true, 0, 6);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (33, 'Chemistry', true, 1, 6);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (34, 'Biology', true, 2, 6);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (35, 'Math', true, 3, 6);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (36, 'Accounting', true, 4, 6);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (37, 'Business Studies', true, 5, 6);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (38, 'Economics', true, 6, 6);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (39, 'Computer Science', true, 7, 6);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (40, 'Informatics Practices', true, 8, 6);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (41, 'Math', true, 0, 7);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (42, 'Physics', true, 1, 7);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (43, 'Chemistry', true, 2, 7);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (44, 'Biology', true, 3, 7);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (45, 'Accounting', true, 4, 7);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (46, 'Business Studies', true, 5, 7);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (47, 'Economics', true, 6, 7);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (48, 'Computer Science', true, 7, 7);
INSERT INTO school_app_aisathisubject (id, name, is_active, "order", class_ref_id) VALUES (49, 'Informatics Practices', true, 8, 7);

INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (1, 'Knowing Our Numbers', 0, true, 1);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (2, 'Whole Numbers', 1, true, 1);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (3, 'Playing with Numbers', 2, true, 1);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (4, 'Basic Geometrical Ideas', 3, true, 1);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (5, 'Understanding Elementary Shapes', 4, true, 1);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (6, 'Integers', 5, true, 1);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (7, 'Fractions', 6, true, 1);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (8, 'Decimals', 7, true, 1);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (9, 'Data Handling', 8, true, 1);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (10, 'Mensuration', 9, true, 1);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (11, 'Algebra', 10, true, 1);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (12, 'Ratio and Proportion', 11, true, 1);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (13, 'Symmetry', 12, true, 1);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (14, 'Practical Geometry', 13, true, 1);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (15, 'Food: Where Does It Come From?', 0, true, 2);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (16, 'Components of Food', 1, true, 2);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (17, 'Fibre to Fabric', 2, true, 2);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (18, 'Sorting Materials into Groups', 3, true, 2);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (19, 'Separation of Substances', 4, true, 2);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (20, 'Changes Around Us', 5, true, 2);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (21, 'Getting to Know Plants', 6, true, 2);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (22, 'Body Movements', 7, true, 2);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (23, 'The Living Organisms and Their Surroundings', 8, true, 2);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (24, 'Motion and Measurement of Distances', 9, true, 2);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (25, 'Light, Shadows and Reflections', 10, true, 2);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (26, 'Electricity and Circuits', 11, true, 2);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (27, 'Fun with Magnets', 12, true, 2);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (28, 'Who Did Patrick''s Homework', 0, true, 3);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (29, 'How the Dog Found Himself', 1, true, 3);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (30, 'Taro''s Reward', 2, true, 3);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (31, 'An Indian-American Woman in Space', 3, true, 3);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (32, 'A Different Kind of School', 4, true, 3);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (33, 'Who I Am', 5, true, 3);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (34, 'Fair Play', 6, true, 3);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (35, 'A Game of Chance', 7, true, 3);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (36, 'Desert Animals', 8, true, 3);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (37, 'The Banyan Tree', 9, true, 3);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (38, 'वह चिड़िया जो', 0, true, 4);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (39, 'बचपन', 1, true, 4);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (40, 'नादान दोस्त', 2, true, 4);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (41, 'चाँद से थोड़ी-सी गप्पें', 3, true, 4);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (42, 'अक्षरों का महत्व', 4, true, 4);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (43, 'पार नज़र के', 5, true, 4);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (44, 'साथी हाथ बढ़ाना', 6, true, 4);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (45, 'मैं हूँ', 7, true, 4);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (46, 'किताब से दोस्ती', 8, true, 4);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (47, 'History: What, Where, How and When', 0, true, 5);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (48, 'From Hunting-Gathering to Growing Food', 1, true, 5);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (49, 'In the Earliest Cities', 2, true, 5);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (50, 'What Books and Burials Tell Us', 3, true, 5);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (51, 'Kingdoms, Kings and an Early Republic', 4, true, 5);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (52, 'Understanding Chakravartin', 5, true, 5);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (53, 'Geography: The Earth in the Solar System', 6, true, 5);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (54, 'Globe: Latitudes and Longitudes', 7, true, 5);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (55, 'Maps', 8, true, 5);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (56, 'Civics: Understanding Diversity', 9, true, 5);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (57, 'Diversity and Discrimination', 10, true, 5);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (58, 'What is Government', 11, true, 5);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (59, 'Key Elements of Democratic Institutions', 12, true, 5);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (60, 'Integers', 0, true, 6);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (61, 'Fractions and Decimals', 1, true, 6);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (62, 'Data Handling', 2, true, 6);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (63, 'Simple Equations', 3, true, 6);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (64, 'Lines and Angles', 4, true, 6);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (65, 'The Triangle and Its Properties', 5, true, 6);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (66, 'Congruence of Triangles', 6, true, 6);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (67, 'Comparing Quantities', 7, true, 6);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (68, 'Rational Numbers', 8, true, 6);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (69, 'Practical Geometry', 9, true, 6);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (70, 'Perimeter and Area', 10, true, 6);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (71, 'Algebraic Expressions', 11, true, 6);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (72, 'Exponents and Powers', 12, true, 6);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (73, 'Symmetry', 13, true, 6);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (74, 'Visualising Solid Shapes', 14, true, 6);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (75, 'Nutrition in Plants', 0, true, 7);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (76, 'Nutrition in Animals', 1, true, 7);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (77, 'Fibre to Fabric', 2, true, 7);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (78, 'Heat', 3, true, 7);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (79, 'Acids, Bases and Salts', 4, true, 7);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (80, 'Physical and Chemical Changes', 5, true, 7);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (81, 'Respiration in Organisms', 6, true, 7);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (82, 'Transportation in Animals and Plants', 7, true, 7);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (83, 'Reproduction in Plants', 8, true, 7);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (84, 'Motion and Time', 9, true, 7);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (85, 'Electric Current and Its Effects', 10, true, 7);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (86, 'Light', 11, true, 7);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (87, 'Forests: Our Lifeline', 12, true, 7);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (88, 'Wastewater Story', 13, true, 7);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (89, 'Three Questions', 0, true, 8);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (90, 'A Gift of Chappals', 1, true, 8);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (91, 'Gopal and the Hilsa Fish', 2, true, 8);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (92, 'The Ashes That Made Trees Bloom', 3, true, 8);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (93, 'Quality', 4, true, 8);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (94, 'Expert Detectives', 5, true, 8);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (95, 'The Invention of Vita-Wonk', 6, true, 8);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (96, 'Keeping It from Harold', 7, true, 8);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (97, 'Chivvy', 8, true, 8);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (98, 'The Rebel', 9, true, 8);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (99, 'हम पंछी उन्मुक्त गगन के', 0, true, 9);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (100, 'दादी माँ', 1, true, 9);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (101, 'हिमालय की बेटियाँ', 2, true, 9);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (102, 'कंचा', 3, true, 9);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (103, 'मीठाईवाला', 4, true, 9);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (104, 'रक्त और हमारा शरीर', 5, true, 9);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (105, 'पापा खो गए', 6, true, 9);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (106, 'साखी', 7, true, 9);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (107, 'वाख', 8, true, 9);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (108, 'ऋतुराज', 9, true, 9);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (109, 'Tracing Changes Through a Thousand Years', 0, true, 10);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (110, 'New Kings and Kingdoms', 1, true, 10);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (111, 'The Delhi Sultanate', 2, true, 10);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (112, 'The Mughal Empire', 3, true, 10);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (113, 'Rulers and Buildings', 4, true, 10);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (114, 'Town, Bazaar and Trade', 5, true, 10);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (115, 'Environment', 6, true, 10);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (116, 'Inside Our Earth', 7, true, 10);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (117, 'Our Changing Earth', 8, true, 10);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (118, 'On Equality', 9, true, 10);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (119, 'Role of the Government in Health', 10, true, 10);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (120, 'How the State Government Works', 11, true, 10);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (121, 'Understanding Media', 12, true, 10);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (122, 'Rational Numbers', 0, true, 11);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (123, 'Linear Equations in One Variable', 1, true, 11);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (124, 'Understanding Quadrilaterals', 2, true, 11);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (125, 'Practical Geometry', 3, true, 11);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (126, 'Data Handling', 4, true, 11);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (127, 'Squares and Square Roots', 5, true, 11);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (128, 'Cubes and Cube Roots', 6, true, 11);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (129, 'Comparing Quantities', 7, true, 11);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (130, 'Algebraic Expressions and Identities', 8, true, 11);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (131, 'Visualising Solid Shapes', 9, true, 11);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (132, 'Mensuration', 10, true, 11);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (133, 'Exponents and Powers', 11, true, 11);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (134, 'Direct and Inverse Proportions', 12, true, 11);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (135, 'Factorisation', 13, true, 11);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (136, 'Introduction to Graphs', 14, true, 11);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (137, 'Playing with Numbers', 15, true, 11);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (138, 'Crop Production and Management', 0, true, 12);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (139, 'Microorganisms: Friend and Foe', 1, true, 12);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (140, 'Synthetic Fibres and Plastics', 2, true, 12);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (141, 'Materials: Metals and Non-Metals', 3, true, 12);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (142, 'Coal and Petroleum', 4, true, 12);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (143, 'Combustion and Flame', 5, true, 12);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (144, 'Cell – Structure and Functions', 6, true, 12);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (145, 'Reproduction in Animals', 7, true, 12);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (146, 'Reaching the Age of Adolescence', 8, true, 12);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (147, 'Force and Pressure', 9, true, 12);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (148, 'Friction', 10, true, 12);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (149, 'Sound', 11, true, 12);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (150, 'Chemical Effects of Electric Current', 12, true, 12);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (151, 'Some Natural Phenomena', 13, true, 12);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (152, 'Conservation of Plants and Animals', 14, true, 12);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (153, 'The Best Christmas Present', 0, true, 13);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (154, 'The Tsunami', 1, true, 13);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (155, 'Glimpses of the Past', 2, true, 13);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (156, 'Bepin Choudhury''s Lapse of Memory', 3, true, 13);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (157, 'The Summit Within', 4, true, 13);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (158, 'The School Play', 5, true, 13);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (159, 'Reaching for the Stars', 6, true, 13);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (160, 'Jalebis', 7, true, 13);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (161, 'Black Aeroplane', 8, true, 13);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (162, 'ध्वनि', 0, true, 14);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (163, 'लाख की चूड़ियाँ', 1, true, 14);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (164, 'बस की यात्रा', 2, true, 14);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (165, 'दीवानों की हस्ती', 3, true, 14);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (166, 'चिट्ठियों की अनूठी दुनिया', 4, true, 14);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (167, 'भगवान के डाकिये', 5, true, 14);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (168, 'क्या निराश हुआ जाए', 6, true, 14);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (169, 'यह दीप अकेला', 7, true, 14);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (170, 'कबीरवाणी', 8, true, 14);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (171, 'संसार', 9, true, 14);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (172, 'How, When and Where', 0, true, 15);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (173, 'The British Took Control', 1, true, 15);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (174, 'Ruling the Roost', 2, true, 15);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (175, 'India After Independence', 3, true, 15);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (176, 'Understanding the Secular State', 4, true, 15);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (177, 'Resources', 5, true, 15);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (178, 'Agriculture', 6, true, 15);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (179, 'Minerals and Power Resources', 7, true, 15);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (180, 'The Indian Constitution', 8, true, 15);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (181, 'Understanding Secularism', 9, true, 15);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (182, 'Vivekananda: His Four Yogas', 10, true, 15);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (183, 'Bhagat Singh: Courage and Sacrifice', 11, true, 15);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (184, 'Introduction to Computers', 0, true, 16);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (185, 'Introduction to Python Programming', 1, true, 16);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (186, 'Python Programming - Data Types and Variables', 2, true, 16);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (187, 'Operators and Expressions', 3, true, 16);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (188, 'Control Structures - Conditional Statements', 4, true, 16);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (189, 'Control Structures - Loops', 5, true, 16);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (190, 'Functions', 6, true, 16);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (191, 'Lists and Strings', 7, true, 16);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (192, 'Dictionaries and Sets', 8, true, 16);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (193, 'File Handling', 9, true, 16);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (194, 'Physical Fitness and Wellness', 0, true, 17);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (195, 'Sports and Games Rules', 1, true, 17);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (196, 'Yoga and its Benefits', 2, true, 17);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (197, 'First Aid and Safety', 3, true, 17);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (198, 'Sports Nutrition', 4, true, 17);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (199, 'Movement and Posture', 5, true, 17);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (200, 'Athletic Skills', 6, true, 17);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (201, 'Team Sports Fundamentals', 7, true, 17);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (202, 'Individual Sports Fundamentals', 8, true, 17);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (203, 'Healthy Lifestyle', 9, true, 17);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (204, 'Number Systems', 0, true, 18);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (205, 'Polynomials', 1, true, 18);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (206, 'Coordinate Geometry', 2, true, 18);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (207, 'Linear Equations in Two Variables', 3, true, 18);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (208, 'Introduction to Euclid''s Geometry', 4, true, 18);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (209, 'Lines and Angles', 5, true, 18);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (210, 'Triangles', 6, true, 18);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (211, 'Quadrilaterals', 7, true, 18);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (212, 'Areas of Parallelograms and Triangles', 8, true, 18);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (213, 'Circles', 9, true, 18);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (214, 'Constructions', 10, true, 18);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (215, 'Heron''s Formula', 11, true, 18);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (216, 'Surface Areas and Volumes', 12, true, 18);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (217, 'Statistics', 13, true, 18);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (218, 'Probability', 14, true, 18);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (219, 'Matter in Our Surroundings', 0, true, 19);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (220, 'Is Matter Around Us Pure', 1, true, 19);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (221, 'Atoms and Molecules', 2, true, 19);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (222, 'Structure of the Atom', 3, true, 19);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (223, 'The Fundamental Unit of Life', 4, true, 19);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (224, 'Tissues', 5, true, 19);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (225, 'Diversity in Living Organisms', 6, true, 19);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (226, 'Why Do We Fall Ill', 7, true, 19);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (227, 'Natural Resources', 8, true, 19);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (228, 'Improvement in Food Resources', 9, true, 19);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (229, 'Motion', 10, true, 19);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (230, 'Force and Laws of Motion', 11, true, 19);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (231, 'Gravitation', 12, true, 19);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (232, 'Work and Energy', 13, true, 19);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (233, 'Sound', 14, true, 19);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (234, 'The Fun They Had', 0, true, 20);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (235, 'The Sound of Music', 1, true, 20);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (236, 'The Little Girl', 2, true, 20);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (237, 'A Truly Beautiful Mind', 3, true, 20);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (238, 'My Childhood', 4, true, 20);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (239, 'Packing', 5, true, 20);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (240, 'Reach for the Top', 6, true, 20);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (241, 'The Bond of Love', 7, true, 20);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (242, 'Katrina', 8, true, 20);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (243, 'If I Were You', 9, true, 20);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (244, 'दो बैलों की कथा', 0, true, 21);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (245, 'ल्हासा की ओर', 1, true, 21);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (246, 'उपभोक्तावाद की संस्कृति', 2, true, 21);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (247, 'साँवले सपनों की याद', 3, true, 21);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (248, 'नाना साहब की पुत्री देवी मैना', 4, true, 21);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (249, 'प्रेमचंद की कहानी उपहार', 5, true, 21);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (250, 'मेरे बचपन के दिन', 6, true, 21);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (251, 'संस्कृति', 7, true, 21);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (252, 'गिरगिट', 8, true, 21);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (253, 'अग्नि पथ', 9, true, 21);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (254, 'The French Revolution', 0, true, 22);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (255, 'Socialism in Europe and the Russian Revolution', 1, true, 22);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (256, 'Nazism and the Rise of Hitler', 2, true, 22);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (257, 'India – Size and Location', 3, true, 22);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (258, 'Physical Features of India', 4, true, 22);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (259, 'Drainage', 5, true, 22);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (260, 'Climate', 6, true, 22);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (261, 'Natural Vegetation and Fauna', 7, true, 22);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (262, 'Population', 8, true, 22);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (263, 'What is Democracy', 9, true, 22);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (264, 'Constitutional Design', 10, true, 22);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (265, 'Electoral Politics', 11, true, 22);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (266, 'Python Programming - Basics', 0, true, 23);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (267, 'Python Programming - Control Structures', 1, true, 23);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (268, 'Functions and Modules', 2, true, 23);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (269, 'Data Structures - Lists and Tuples', 3, true, 23);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (270, 'Data Structures - Dictionaries and Sets', 4, true, 23);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (271, 'File Handling', 5, true, 23);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (272, 'Error Handling and Exceptions', 6, true, 23);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (273, 'Object-Oriented Programming Concepts', 7, true, 23);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (274, 'Database Concepts', 8, true, 23);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (275, 'Networking Basics', 9, true, 23);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (276, 'Physical Fitness - Cardiovascular Endurance', 0, true, 24);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (277, 'Physical Fitness - Muscular Strength', 1, true, 24);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (278, 'Physical Fitness - Flexibility', 2, true, 24);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (279, 'Yoga - Asanas and Benefits', 3, true, 24);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (280, 'Sports - Athletics and Games', 4, true, 24);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (281, 'Sports - Racket Games', 5, true, 24);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (282, 'Sports - Aquatic Activities', 6, true, 24);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (283, 'First Aid in Sports', 7, true, 24);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (284, 'Nutrition and Health', 8, true, 24);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (285, 'Mental Health and Stress Management', 9, true, 24);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (286, 'Real Numbers', 0, true, 25);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (287, 'Polynomials', 1, true, 25);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (288, 'Pair of Linear Equations in Two Variables', 2, true, 25);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (289, 'Quadratic Equations', 3, true, 25);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (290, 'Arithmetic Progressions', 4, true, 25);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (291, 'Triangles', 5, true, 25);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (292, 'Coordinate Geometry', 6, true, 25);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (293, 'Trigonometry', 7, true, 25);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (294, 'Applications of Trigonometry', 8, true, 25);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (295, 'Circles', 9, true, 25);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (296, 'Constructions', 10, true, 25);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (297, 'Areas Related to Circles', 11, true, 25);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (298, 'Surface Areas and Volumes', 12, true, 25);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (299, 'Statistics', 13, true, 25);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (300, 'Probability', 14, true, 25);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (301, 'Chemical Reactions and Equations', 0, true, 26);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (302, 'Acids, Bases and Salts', 1, true, 26);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (303, 'Metals and Non-Metals', 2, true, 26);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (304, 'Carbon and Its Compounds', 3, true, 26);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (305, 'Life Processes', 4, true, 26);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (306, 'Control and Coordination', 5, true, 26);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (307, 'How Do Organisms Reproduce', 6, true, 26);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (308, 'Heredity and Evolution', 7, true, 26);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (309, 'Light – Reflection and Refraction', 8, true, 26);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (310, 'The Human Eye and the Colourful World', 9, true, 26);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (311, 'Electricity', 10, true, 26);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (312, 'Magnetic Effects of Electric Current', 11, true, 26);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (313, 'Sources of Energy', 12, true, 26);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (314, 'Our Environment', 13, true, 26);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (315, 'Management of Natural Resources', 14, true, 26);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (316, 'A Letter to God', 0, true, 27);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (317, 'Nelson Mandela: A Long Walk to Freedom', 1, true, 27);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (318, 'Two Stories About Flying', 2, true, 27);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (319, 'From a Railway Carriage & The Road Not Taken', 3, true, 27);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (320, 'A Tiger in the House', 4, true, 27);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (321, 'The Midnight Visitor', 5, true, 27);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (322, 'Bholi', 6, true, 27);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (323, 'The Book That Saved My Life', 7, true, 27);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (324, 'The Proposal', 8, true, 27);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (325, 'The Necklace', 9, true, 27);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (326, 'पद', 0, true, 28);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (327, 'राम-लक्ष्मण-परशुराम संवाद', 1, true, 28);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (328, 'आत्मत्राण', 2, true, 28);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (329, 'उत्साह और हिमालय', 3, true, 28);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (330, 'यमराज का दूत', 4, true, 28);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (331, 'छायावाद', 5, true, 28);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (332, 'छायावाद काव्य संग्रह', 6, true, 28);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (333, 'आदमी का मूल्य', 7, true, 28);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (334, 'नेताजी का चश्मा', 8, true, 28);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (335, 'बड़े भाई साहब', 9, true, 28);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (336, 'डायरी का एक पन्ना', 10, true, 28);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (337, 'ल्हासा की ओर', 11, true, 28);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (338, 'The Rise of Nationalism in Europe', 0, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (339, 'The Indus Valley Civilization', 1, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (340, 'The Vedic Age', 2, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (341, 'Early Kingdoms', 3, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (342, 'The Mauryan Empire', 4, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (343, 'The Post Mauryan Period', 5, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (344, 'The Sultanate Period', 6, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (345, 'The Mughal Empire', 7, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (346, 'Colonialism', 8, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (347, 'The British Raj', 9, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (348, 'The Revolt of 1857', 10, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (349, 'Indian National Movement', 11, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (350, 'Resources and Development', 12, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (351, 'Forest and Wildlife', 13, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (352, 'Water Resources', 14, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (353, 'Mineral and Energy Resources', 15, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (354, 'Agriculture', 16, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (355, 'Democratic Politics', 17, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (356, 'Power Sharing Arrangements', 18, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (357, 'Competition Among Political Parties', 19, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (358, 'Challenges to Democracy', 20, true, 29);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (359, 'Introduction to Algorithm and Flowchart', 0, true, 30);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (360, 'Fundamentals of Python Programming', 1, true, 30);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (361, 'Python - Data Types and Variables', 2, true, 30);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (362, 'Python - Control Structures', 3, true, 30);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (363, 'Functions and Parameters', 4, true, 30);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (364, 'Strings and String Manipulation', 5, true, 30);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (365, 'Lists and Tuples', 6, true, 30);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (366, 'Dictionaries and Sets', 7, true, 30);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (367, 'File Handling and Exception Handling', 8, true, 30);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (368, 'Introduction to Database Management Systems', 9, true, 30);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (369, 'Planning and Organization of Physical Education', 0, true, 31);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (370, 'Physical Fitness Assessment', 1, true, 31);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (371, 'Training Principles and Adaptations', 2, true, 31);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (372, 'Sports and Games - Rules and Techniques', 3, true, 31);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (373, 'Yoga for Health and Wellness', 4, true, 31);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (374, 'First Aid and Safety Measures', 5, true, 31);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (375, 'Health and Nutrition for Athletes', 6, true, 31);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (376, 'Stress Management and Relaxation', 7, true, 31);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (377, 'Performance Appraisal', 8, true, 31);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (378, 'Life Skills and Character Development', 9, true, 31);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (379, 'Physical World and Measurement', 0, true, 32);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (380, 'Kinematics', 1, true, 32);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (381, 'Laws of Motion', 2, true, 32);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (382, 'Work, Energy and Power', 3, true, 32);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (383, 'Motion of System of Particles and Rigid Body', 4, true, 32);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (384, 'Gravitation', 5, true, 32);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (385, 'Properties of Bulk Matter – Elasticity', 6, true, 32);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (386, 'Properties of Bulk Matter – Fluid Pressure', 7, true, 32);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (387, 'Thermal Properties of Matter', 8, true, 32);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (388, 'Thermodynamics', 9, true, 32);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (389, 'Kinetic Theory of Gases', 10, true, 32);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (390, 'Oscillations', 11, true, 32);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (391, 'Waves', 12, true, 32);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (392, 'Some Basic Concepts of Chemistry', 0, true, 33);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (393, 'Structure of Atom', 1, true, 33);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (394, 'Classification of Elements and Periodicity in Properties', 2, true, 33);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (395, 'Chemical Bonding and Molecular Structure', 3, true, 33);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (396, 'States of Matter', 4, true, 33);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (397, 'Thermodynamics', 5, true, 33);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (398, 'Equilibrium', 6, true, 33);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (399, 'Redox Reactions', 7, true, 33);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (400, 'Hydrogen', 8, true, 33);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (401, 'The s-Block Element', 9, true, 33);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (402, 'The p-Block Element – Group 13 and 14', 10, true, 33);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (403, 'Organic Chemistry: Some Basic Principles and Techniques', 11, true, 33);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (404, 'Hydrocarbons', 12, true, 33);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (405, 'Environmental Chemistry', 13, true, 33);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (406, 'The Living World', 0, true, 34);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (407, 'Biological Classification', 1, true, 34);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (408, 'Plant Kingdom', 2, true, 34);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (409, 'Animal Kingdom', 3, true, 34);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (410, 'Morphology of Flowering Plants', 4, true, 34);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (411, 'Anatomy of Flowering Plants', 5, true, 34);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (412, 'Structural Organisation in Animals', 6, true, 34);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (413, 'Cell: The Unit of Life', 7, true, 34);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (414, 'Biomolecules', 8, true, 34);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (415, 'Cell Cycle and Cell Division', 9, true, 34);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (416, 'Transport in Plants', 10, true, 34);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (417, 'Mineral Nutrition', 11, true, 34);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (418, 'Photosynthesis in Higher Plants', 12, true, 34);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (419, 'Respiration in Plants', 13, true, 34);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (420, 'Plant Growth and Development', 14, true, 34);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (421, 'Sets', 0, true, 35);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (422, 'Relations and Functions', 1, true, 35);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (423, 'Trigonometric Functions', 2, true, 35);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (424, 'Principle of Mathematical Induction', 3, true, 35);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (425, 'Complex Numbers and Quadratic Equations', 4, true, 35);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (426, 'Linear Inequalities', 5, true, 35);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (427, 'Permutations and Combinations', 6, true, 35);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (428, 'Binomial Theorem', 7, true, 35);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (429, 'Sequences and Series', 8, true, 35);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (430, 'Straight Lines', 9, true, 35);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (431, 'Conic Sections', 10, true, 35);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (432, 'Introduction to Three Dimensional Geometry', 11, true, 35);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (433, 'Limits and Derivatives', 12, true, 35);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (434, 'Mathematical Reasoning', 13, true, 35);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (435, 'Statistics', 14, true, 35);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (436, 'Probability', 15, true, 35);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (437, 'Introduction to Accounting', 0, true, 36);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (438, 'Theory Base of Accounting', 1, true, 36);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (439, 'Recording of Transactions - I', 2, true, 36);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (440, 'Recording of Transactions - II', 3, true, 36);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (441, 'Bank Reconciliation Statement', 4, true, 36);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (442, 'Trial Balance and Rectification of Errors', 5, true, 36);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (443, 'Depreciation, Provisions and Reserves', 6, true, 36);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (444, 'Bills of Exchange', 7, true, 36);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (445, 'Final Accounts - I', 8, true, 36);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (446, 'Final Accounts - II', 9, true, 36);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (447, 'Final Accounts - III', 10, true, 36);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (448, 'Accounts of Not-for-Profit Organizations', 11, true, 36);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (449, 'Partnership Accounts - Fundamentals', 12, true, 36);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (450, 'Partnership Accounts - Admission of a Partner', 13, true, 36);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (451, 'Nature and Significance of Management', 0, true, 37);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (452, 'Principles of Management', 1, true, 37);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (453, 'Business Environment', 2, true, 37);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (454, 'Planning', 3, true, 37);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (455, 'Organising', 4, true, 37);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (456, 'Staffing', 5, true, 37);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (457, 'Directing', 6, true, 37);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (458, 'Controlling', 7, true, 37);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (459, 'Financial Management', 8, true, 37);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (460, 'Financial Planning', 9, true, 37);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (461, 'Working Capital Management', 10, true, 37);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (462, 'Marketing Management', 11, true, 37);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (463, 'Consumer Protection', 12, true, 37);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (464, 'Introduction to Economics', 0, true, 38);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (465, 'Consumer Equilibrium and Demand', 1, true, 38);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (466, 'Producer Equilibrium and Supply', 2, true, 38);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (467, 'The Market Forms and Price Determination', 3, true, 38);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (468, 'National Income Accounting', 4, true, 38);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (469, 'Money Supply and Inflation', 5, true, 38);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (470, 'Banking and Finance', 6, true, 38);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (471, 'Government Budget and Fiscal Policy', 7, true, 38);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (472, 'Balance of Payments', 8, true, 38);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (473, 'Aggregate Demand and Supply', 9, true, 38);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (474, 'Computer Organization and Architecture', 0, true, 39);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (475, 'Boolean Algebra and Logic Gates', 1, true, 39);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (476, 'Programming in Python - Basics', 2, true, 39);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (477, 'Programming in Python - Data Structures', 3, true, 39);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (478, 'Database Management Systems', 4, true, 39);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (479, 'Computer Networks', 5, true, 39);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (480, 'Web Technologies', 6, true, 39);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (481, 'Software Engineering', 7, true, 39);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (482, 'Cybersecurity', 8, true, 39);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (483, 'Introduction to Informatics Practices', 0, true, 40);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (484, 'Database Concepts', 1, true, 40);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (485, 'Structured Query Language - Basics', 2, true, 40);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (486, 'Structured Query Language - Advanced', 3, true, 40);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (487, 'Web Applications', 4, true, 40);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (488, 'Software Development', 5, true, 40);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (489, 'Cloud Computing', 6, true, 40);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (490, 'Cybersecurity Fundamentals', 7, true, 40);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (491, 'Data Analysis and Visualization', 8, true, 40);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (492, 'Relations and Functions', 0, true, 41);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (493, 'Inverse Trigonometric Functions', 1, true, 41);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (494, 'Matrices', 2, true, 41);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (495, 'Determinants', 3, true, 41);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (496, 'Continuity and Differentiability', 4, true, 41);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (497, 'Applications of Derivatives', 5, true, 41);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (498, 'Integrals', 6, true, 41);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (499, 'Applications of Integrals', 7, true, 41);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (500, 'Differential Equations', 8, true, 41);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (501, 'Vector Algebra', 9, true, 41);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (502, 'Three Dimensional Geometry', 10, true, 41);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (503, 'Linear Programming', 11, true, 41);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (504, 'Probability', 12, true, 41);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (505, 'Electric Charges and Fields', 0, true, 42);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (506, 'Electrostatic Potential and Capacitance', 1, true, 42);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (507, 'Current Electricity', 2, true, 42);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (508, 'Moving Charges and Magnetism', 3, true, 42);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (509, 'Magnetism and Matter', 4, true, 42);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (510, 'Electromagnetic Induction', 5, true, 42);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (511, 'Alternating Current', 6, true, 42);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (512, 'Electromagnetic Waves', 7, true, 42);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (513, 'Ray Optics and Optical Instruments', 8, true, 42);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (514, 'Wave Optics', 9, true, 42);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (515, 'Dual Nature of Radiation and Matter', 10, true, 42);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (516, 'Atoms', 11, true, 42);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (517, 'Nuclei', 12, true, 42);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (518, 'Semiconductor Electronics', 13, true, 42);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (519, 'Solid State', 0, true, 43);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (520, 'Solutions', 1, true, 43);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (521, 'Electrochemistry', 2, true, 43);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (522, 'Chemical Kinetics', 3, true, 43);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (523, 'Surface Chemistry', 4, true, 43);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (524, 'General Principles and Processes of Isolation of Elements', 5, true, 43);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (525, 'The p-Block Elements', 6, true, 43);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (526, 'The d- and f-Block Elements', 7, true, 43);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (527, 'Coordination Compounds', 8, true, 43);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (528, 'Haloalkanes and Haloarenes', 9, true, 43);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (529, 'Alcohols, Phenols and Ethers', 10, true, 43);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (530, 'Aldehydes, Ketones and Carboxylic Acids', 11, true, 43);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (531, 'Amines', 12, true, 43);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (532, 'Biomolecules', 13, true, 43);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (533, 'Polymers', 14, true, 43);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (534, 'Chemistry in Everyday Life', 15, true, 43);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (535, 'Reproduction in Organisms', 0, true, 44);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (536, 'Sexual Reproduction in Flowering Plants', 1, true, 44);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (537, 'Human Reproduction', 2, true, 44);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (538, 'Reproductive Health', 3, true, 44);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (539, 'Principles of Inheritance and Variation', 4, true, 44);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (540, 'Molecular Basis of Inheritance', 5, true, 44);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (541, 'Evolution', 6, true, 44);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (542, 'Human Health and Disease', 7, true, 44);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (543, 'Strategies for Enhancement in Food Production', 8, true, 44);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (544, 'Microbes in Human Welfare', 9, true, 44);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (545, 'Biotechnology: Principles and Processes', 10, true, 44);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (546, 'Biotechnology and Its Applications', 11, true, 44);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (547, 'Organisms and Populations', 12, true, 44);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (548, 'Ecosystem', 13, true, 44);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (549, 'Biodiversity and Conservation', 14, true, 44);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (550, 'Environmental Issues', 15, true, 44);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (551, 'Accounting for Partnership Firms - Fundamentals', 0, true, 45);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (552, 'Reconstitution of Partnership - Retirement/Death', 1, true, 45);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (553, 'Dissolution of Partnership Firm', 2, true, 45);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (554, 'Accounting for Share Capital', 3, true, 45);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (555, 'Accounting for Debentures', 4, true, 45);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (556, 'Financial Statements of a Company', 5, true, 45);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (557, 'Analysis of Financial Statements – I', 6, true, 45);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (558, 'Analysis of Financial Statements – II', 7, true, 45);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (559, 'Cash Flow Statement', 8, true, 45);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (560, 'Accounting Ratios', 9, true, 45);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (561, 'Accounts from Incomplete Records', 10, true, 45);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (562, 'Corporate Governance and Business Ethics', 0, true, 46);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (563, 'Financial Management and Analysis', 1, true, 46);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (564, 'Business Administration', 2, true, 46);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (565, 'Consumer Protection', 3, true, 46);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (566, 'Entrepreneurship', 4, true, 46);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (567, 'Strategic Management', 5, true, 46);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (568, 'International Business', 6, true, 46);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (569, 'Supply Chain Management', 7, true, 46);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (570, 'Corporate Responsibility and Sustainability', 8, true, 46);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (571, 'Marketing Strategy', 9, true, 46);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (572, 'Macroeconomics - Introduction', 0, true, 47);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (573, 'National Income Accounting', 1, true, 47);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (574, 'Money and Inflation', 2, true, 47);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (575, 'Banking System', 3, true, 47);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (576, 'Government Budget', 4, true, 47);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (577, 'Foreign Exchange and Balance of Payments', 5, true, 47);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (578, 'Aggregate Demand and Supply', 6, true, 47);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (579, 'Consumption and Investment Functions', 7, true, 47);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (580, 'Aggregate Demand and Output', 8, true, 47);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (581, 'Monetary Policy and Fiscal Policy', 9, true, 47);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (582, 'Python Programming - Advanced', 0, true, 48);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (583, 'Object-Oriented Programming', 1, true, 48);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (584, 'Data Structures and Algorithms', 2, true, 48);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (585, 'Databases and SQL', 3, true, 48);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (586, 'Web Development', 4, true, 48);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (587, 'Cybersecurity and Cryptography', 5, true, 48);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (588, 'Artificial Intelligence and Machine Learning', 6, true, 48);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (589, 'Software Engineering Practices', 7, true, 48);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (590, 'Cloud Computing and IoT', 8, true, 48);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (591, 'Advanced Database Concepts', 0, true, 49);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (592, 'Data Analytics with Python', 1, true, 49);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (593, 'Web Development with HTML, CSS and JavaScript', 2, true, 49);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (594, 'Backend Development', 3, true, 49);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (595, 'Mobile Application Development', 4, true, 49);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (596, 'Cloud Technologies', 5, true, 49);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (597, 'Security in Applications', 6, true, 49);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (598, 'Big Data Fundamentals', 7, true, 49);
INSERT INTO school_app_aisathichapter (id, name, "order", is_active, subject_id) VALUES (599, 'IoT and Smart Systems', 8, true, 49);
-- ============================================================
-- STEP 3: Reset sequences so future inserts get correct IDs
-- ============================================================

SELECT setval(pg_get_serial_sequence('school_app_aisathiclass',   'id'), MAX(id)) FROM school_app_aisathiclass;
SELECT setval(pg_get_serial_sequence('school_app_aisathisubject',  'id'), MAX(id)) FROM school_app_aisathisubject;
SELECT setval(pg_get_serial_sequence('school_app_aisathichapter',  'id'), MAX(id)) FROM school_app_aisathichapter;
